workflows:
  ios_release:
    name: "Flutter iOS Build"
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.ar.emicardigital.recibodigital"
      groups:
        - manual_signing_credentials

    scripts:
      - name: Instalar dependencias de Flutter
        script: |
          flutter clean
          flutter pub get

      - name: Fix CocoaPods Configuration
        script: |
          echo '#include "Pods/Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig"' >> ios/Flutter/Release.xcconfig

      - name: Instalar dependencias de iOS
        script: |
          cd ios
          pod repo update
          pod install

      - name: Compilar app sin firmar (Flutter)
        script: |
          flutter build ios --release --no-codesign

      - name: Crear archivo .xcarchive con firma de distribución
        script: |
          xcodebuild archive \
            -project ios/Runner.xcodeproj \
            -scheme Runner \
            -configuration Release \
            -archivePath build/ios/archive/Runner.xcarchive \
            -destination 'generic/platform=iOS' \
            -allowProvisioningUpdates \
            -skipUnavailableActions \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            PROVISIONING_PROFILE="${PROFILE_UUID}" \
            DEVELOPMENT_TEAM=ZU63U9L4QR

      - name: Exportar IPA firmado
        script: |
          xcodebuild -exportArchive \
            -archivePath build/ios/archive/Runner.xcarchive \
            -exportOptionsPlist ios/ExportOptions.plist \
            -exportPath build/ios/ipa

    artifacts:
      - build/ios/ipa/*.ipa
        
publishing:
  app_store_connect:
    auth:
      key_id: $APP_STORE_KEY_ID
      issuer_id: $APP_STORE_ISSUER_ID
      private_key: $APP_STORE_PRIVATE_KEY
    submit_to_testflight: true
    submit_to_app_store: false

email:
  recipients:
    - "mercedariodigital@gmail.com"