workflows:
  ios_release:
    name: "Flutter iOS Build"
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.ar.emicardigital.recibodigital"
      groups:
        - app_store_connect_credentials

    scripts:
      - name: Instalar dependencias de Flutter
        script: |
          flutter clean
          flutter pub get

      - name: Fix CocoaPods Configuration
        script: |
          echo '#include "Pods/Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig"' >> ios/Flutter/Release.xcconfig

      - name: Instalar dependencias de iOS
        script: |
          cd ios
          pod repo update
          pod install

      - name: Compilar IPA para iOS sin firmar (firma la hace Codemagic)
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/iphoneos/*.app
      - build/ios/archive/*.xcarchive

publishing:
      app_store_connect:
        auth:
          key_id: "QQ4RL9JCF6"
          issuer_id: "cebc2c1b-152d-4395-a8d1-7450a3796177"
          private_key: "MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQglMnn+drtsgAYV+M0BUutckvm360h4G/RiNknHVsH/fugCgYIKoZIzj0DAQehRANCAART+v1fA5Ffiooji8Hwh8NxP4RduZvXg4/1X3I+y1AGo19yV35DaXJnFoRHhjtoIidVyNOXmFOjAbhBYkpRq5O9"
        submit_to_testflight: true
        submit_to_app_store: false

email:
  recipients:
  - "mercedariodigital@gmail.com"