workflows:
  ios_release:
    name: "Flutter iOS Build"
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.ar.emicardigital.recibodigital"
      groups:
        - app_store_connect_credentials

    scripts:
      - name: Instalar dependencias de Flutter
        script: |
          flutter clean
          flutter pub get

      - name: Fix CocoaPods Configuration
        script: |
          echo '#include "Pods/Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig"' >> ios/Flutter/Release.xcconfig

      - name: Instalar dependencias de iOS
        script: |
          cd ios
          pod install

      - name: Build y firmar IPA automáticamente
        script: |
          flutter build ipa \
            --release \
            --export-options-plist=ios/ExportOptions.plist

    artifacts:
      - build/ios/ipa/*.ipa
        
publishing:
  app_store_connect:
    auth:
      key_id: $APP_STORE_KEY_ID
      issuer_id: $APP_STORE_ISSUER_ID
      private_key: $APP_STORE_PRIVATE_KEY
    submit_to_testflight: true
    submit_to_app_store: false

email:
  recipients:
    - "mercedariodigital@gmail.com"