workflows:
  ios-workflow:
    name: ReciboDigital iOS Build
    instance_type: mac_mini_m2
    max_build_duration: 120

    integrations:
      app_store_connect: ReciboDigital iOS Build

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.ar.emicardigital.recibodigital
      vars:
        APP_ID: 6748967014  # <-- Reemplazá por tu App ID numérico real de App Store Connect
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Configurar firma automática en Xcode
        script: |
          xcode-project use-profiles

      - name: Obtener paquetes Flutter
        script: |
          flutter pub get

      - name: Instalar pods iOS
        script: |
          find . -name "Podfile" -execdir pod install \;

      - name: Análisis estático Flutter
        script: |
          flutter analyze

      - name: Compilar IPA firmada y versionar automáticamente
        script: |
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=$(($(app-store-connect get-latest-testflight-build-number --platform=IOS "$APP_ID") + 1)) \
            --export-options-plist=/Users/builder/export_options.plist
            
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

    publishing:
      email:
        recipients:
          - mercedariodigital@gmail.com
        notify:
          success: true
          failure: true

      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
        submit_to_app_store: false