// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2Geob6ki1GBN2YAMdyeD0FM-tReJB_KU',
    appId: '1:795591101758:web:0e843efa5bc6ee5848706f',
    messagingSenderId: '795591101758',
    projectId: 'recibo-digital-838ac',
    authDomain: 'recibo-digital-838ac.firebaseapp.com',
    storageBucket: 'recibo-digital-838ac.firebasestorage.app',
    measurementId: 'G-VSZKHTNJ3K',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEAH015WGYUiR8iuD9CScdtbEEVg0EdMY',
    appId: '1:795591101758:ios:3519fb8df246533b48706f',
    messagingSenderId: '795591101758',
    projectId: 'recibo-digital-838ac',
    storageBucket: 'recibo-digital-838ac.firebasestorage.app',
    iosBundleId: 'com.example.reciboDigital',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2Geob6ki1GBN2YAMdyeD0FM-tReJB_KU',
    appId: '1:795591101758:web:d9f60b5a7832e14048706f',
    messagingSenderId: '795591101758',
    projectId: 'recibo-digital-838ac',
    authDomain: 'recibo-digital-838ac.firebaseapp.com',
    storageBucket: 'recibo-digital-838ac.firebasestorage.app',
    measurementId: 'G-NB8W2GKVM1',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEAH015WGYUiR8iuD9CScdtbEEVg0EdMY',
    appId: '1:795591101758:ios:4a9a5369bb4a31eb48706f',
    messagingSenderId: '795591101758',
    projectId: 'recibo-digital-838ac',
    storageBucket: 'recibo-digital-838ac.firebasestorage.app',
    iosBundleId: 'com.ar.emicardigital.recibodigital',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7fyR0os7ugQr1vZl3rvg1YL8PV19jvKA',
    appId: '1:795591101758:android:0b5a1d9f97729c2248706f',
    messagingSenderId: '795591101758',
    projectId: 'recibo-digital-838ac',
    storageBucket: 'recibo-digital-838ac.firebasestorage.app',
  );

}