workspace 'Runner.xcworkspace'

platform :ios, '13.0'

install! 'cocoapods', :deterministic_uuids => false
pod 'FirebaseCore', :modular_headers => true

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_root = File.expand_path('..', File.dirname(__FILE__))
  flutter_application_path = File.absolute_path(File.join(flutter_root, '..'))
  ios_frameworks_path = File.join(flutter_application_path, '.ios', 'Flutter')
    
end
