workspace 'Runner.xcworkspace'

platform :ios, '13.0'


require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

install! 'cocoapods', :warn_for_unused_master_specs_repo => false

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  
  flutter_root = File.expand_path('..', File.dirname(__FILE__))
  flutter_application_path = File.absolute_path(File.join(flutter_root, '..'))
  ios_frameworks_path = File.join(flutter_application_path, '.ios', 'Flutter')
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
    
end